# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('calory', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('weight', models.FloatField()),
                ('energy', models.FloatField()),
                ('protein', models.FloatField()),
                ('carb', models.FloatField()),
                ('fat', models.FloatField()),
                ('saturatedFat', models.FloatField()),
                ('sugar', models.FloatField()),
                ('fibre', models.FloatField()),
                ('cholesterol', models.FloatField()),
                ('calcium', models.FloatField()),
                ('iron', models.FloatField()),
                ('sodium', models.FloatField()),
                ('potassium', models.FloatField()),
                ('magnesium', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('thiamin', models.FloatField()),
                ('riboflavin', models.FloatField()),
                ('niacin', models.FloatField()),
                ('folate', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='inclusion',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ingredient'),
        ),
        migrations.AddField(
            model_name='food',
            name='ingredients',
            field=models.ManyToManyField(through='api.Inclusion', to='api.Ingredient'),
        ),
    ]
