# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161106_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='calory',
        ),
    ]
