# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 01:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_food_calory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inclusion',
            unique_together=set([('food', 'ingredient')]),
        ),
    ]
