# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20161106_0140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Micronutrient',
        ),
        migrations.RenameField(
            model_name='inclusion',
            old_name='weight',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='weight',
            new_name='value',
        ),
        migrations.AddField(
            model_name='inclusion',
            name='unit',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(default='g', max_length=32),
            preserve_default=False,
        ),
    ]
