# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_atefood_ateingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
