# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20161122_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit',
            new_name='defaultUnit',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='value',
            new_name='defaultValue',
        ),
    ]
