# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20161122_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='measureValue',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
