# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_ingredient_measurevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='measureUnit',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
