# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20161204_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
