# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_restaurant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
