# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 16:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0018_food_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('minEnergy', models.FloatField()),
                ('maxEnergy', models.FloatField()),
                ('minProteinVal', models.FloatField()),
                ('maxProteinVal', models.FloatField()),
                ('minCarbVal', models.FloatField()),
                ('maxCarbVal', models.FloatField()),
                ('minFatVal', models.FloatField()),
                ('maxFatVal', models.FloatField()),
                ('minProteinRate', models.FloatField()),
                ('maxProteinRate', models.FloatField()),
                ('minCarbRate', models.FloatField()),
                ('maxCarbRate', models.FloatField()),
                ('minFatRate', models.FloatField()),
                ('maxFatRate', models.FloatField()),
                ('ingredients', models.ManyToManyField(to='api.Ingredient')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
