# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_diet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diet',
            old_name='user',
            new_name='users',
        ),
    ]
