# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20161215_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='tags',
        ),
        migrations.AddField(
            model_name='food',
            name='tags',
            field=models.ManyToManyField(to='api.Tag'),
        ),
    ]
